# Generated by Django 2.2.8 on 2019-12-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictDistricts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва району')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Словник районів',
                'db_table': 'dit_dict_districts',
            },
        ),
        migrations.CreateModel(
            name='DictStreetGeomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип геометрії')),
            ],
            options={
                'verbose_name': 'Тип геометрії',
                'verbose_name_plural': 'Словник типів геометрій',
                'db_table': 'dit_dict_street_geom_type',
            },
        ),
        migrations.CreateModel(
            name='DictStreetOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва операції')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Опис операції')),
            ],
            options={
                'verbose_name': 'Тип операції',
                'verbose_name_plural': 'Словник типів операцій',
                'db_table': 'dit_dict_street_operations',
            },
        ),
        migrations.CreateModel(
            name='DictStreetTopocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Топокод')),
            ],
            options={
                'verbose_name': 'Топокод',
                'verbose_name_plural': 'Словник топокодів',
                'db_table': 'dit_dict_street_topocode',
            },
        ),
        migrations.CreateModel(
            name='DictStreetTract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип тракту')),
            ],
            options={
                'verbose_name': 'Тип тракту',
                'verbose_name_plural': 'Словник типів тракту',
                'db_table': 'dit_dict_street_tract',
            },
        ),
        migrations.CreateModel(
            name='DictStreetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип вулиці')),
            ],
            options={
                'verbose_name': 'Тип Вулиці',
                'verbose_name_plural': 'Словник типів вулиць',
                'db_table': 'dit_dict_street_type',
            },
        ),
    ]
